# Capstone Project Python

## Task 1
Make ***three Dataframe*** in python and ***save*** them as three different ***.csv files.***

In [1]:
# import librarys 
import pandas as pd
import numpy as np

In [2]:
# Data Dictionary for Project DataFrame. (contaning keys as the column name and values as data values)
project_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005", "A002", "A005", "A003", "A001", "A003", "A001", "A004", "A004", "A005"],
    "Project": ["Project 1", "Project 2", "Project 3", "Project 4", "Project 5", "Project 6", "Project 7", "Project 8", "Project 9", "Project 10", "Project 11", "Project 12", "Project 13", "Project 14"],
    "Cost": [1002000, 2000000, 4500000, 5500000, np.nan, 680000, 400000, 350000, np.nan,300000, 2000000, 1000000, 3000000, 200000],
    "Status": ["Finished", "Ongoing", "Finished", "Ongoing", "Finished", "Failed", "Finished", "Failed", "Ongoing", "Finished", "Failed", "Ongoing", "Finished", "Finished"]
}

# Create a dataframe using DataFrame class (two-dimensional) for project data into variable project
project = pd.DataFrame(project_data)

In [3]:
# Output:    Project DataFrame
project

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [4]:
# Data Dictionary for Employee DataFrame. (contaning keys as the column name and values as data values)
employee_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],
    "Name": ["John Alter", "Alice Luxumberg", "Tom Sabestine", "Nina Adgra", "Amy Johny"],
    "Gender": ["M", "F", "M", "F", "F"],
    "City": ["Paris", "London", "Berlin", "Newyork", "Madrid"],
    "Age": [25, 27, 29, 31, 30]
}

# Create a dataframe using DataFrame class (two-dimensional) for employee data into variable employee
employee = pd.DataFrame(employee_data)

In [5]:
#Output:    employee DataFrame
employee

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [6]:
# Data Dictionary for Seniority Level DataFrame. (contaning keys as the column name and values as data values)
seniority_level_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],
    "Designation Level": [2, 2, 3, 2, 3]
}

# Create a dataframe using DataFrame class (two-dimensional) for Seniority Level data into variable seniority_level
seniority_level = pd.DataFrame(seniority_level_data)

In [7]:
# Output:    seniority_level Dataframe
seniority_level

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [8]:
# Save each dataframe into a csv file
project.to_csv("Project.csv", index = False)                # here index = False removes the index column from the csv file Created
employee.to_csv("Employee.csv", index = False)
seniority_level.to_csv("Seniority_Level.csv", index = False)

## Task 2
Compute the ***missing values*** by ***running average*** in column **Cost** using ***"For" loop***

In [9]:
# Load Project Data
project = pd.read_csv("Project.csv")                  # pd.read_csv("file_name.extension")

In [10]:
# Computing missing values by running average in column Cost using "For" loop

# initialize running Total and count variable for itteration
running_total = 0
count = 0

In [11]:
# Loop thorugh each row to fill missing cost 
for avg_cost in range(len(project)):
    if pd.isnull(project.loc[avg_cost, "Cost"]):
        running_avg = running_total / count if count > 0 else 0
        project.loc[avg_cost, "Cost"] = running_avg
    else:
        running_total += project.loc[avg_cost, "Cost"]
        count += 1

In [12]:
# Save the updated dataframe
project.to_csv("Project.csv", index = False)

In [13]:
# Output: Task 2
project

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  3.250500e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  2.061714e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

## Task 3
***Split*** the column ***"Name"*** from the **employee** dataframe into ***"First_Name"*** and ***"Last_Name"***

In [14]:
# load Employee Data
employee = pd.read_csv("Employee.csv")

In [15]:
# Split the Column Name into first name and last name 
employee[["First Name", "Last Name"]] = employee["Name"].str.split(' ', n = 1, expand = True)     # using string manuplation method str.split()

In [16]:
# Output:     (After Spliting Name into First Name and Last Name Columns)
employee

     ID             Name Gender     City  Age First Name  Last Name
0  A001       John Alter      M    Paris   25       John      Alter
1  A002  Alice Luxumberg      F   London   27      Alice  Luxumberg
2  A003    Tom Sabestine      M   Berlin   29        Tom  Sabestine
3  A004       Nina Adgra      F  Newyork   31       Nina      Adgra
4  A005        Amy Johny      F   Madrid   30        Amy      Johny

In [17]:
# remove Name column from the employee file (drop() axis = 1 inplace = True)
employee.drop(columns = ["Name"], inplace = True)

In [18]:
# Save the updated dataframe
employee.to_csv("Employee.csv", index = False)

In [19]:
# Output:   (after droping Name column)
employee

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

## Task 4 
***Join*** all 3 DataFrame into a Single Dataframe and name it as ***"Final"***

In [20]:
# first load all the three dataframe that needs to be merged
project = pd.read_csv("Project.csv")                  # loading all the three file as we are merging them to one final file
employee = pd.read_csv("Employee.csv")
seniority_level = pd.read_csv("Seniority_Level.csv")

In [21]:
# lets make a final dataframe using merge to join the tables by ID column
final = pd.merge(project, employee, on = "ID", how = "left")            # merging project and employee on "ID" using left join

In [22]:
# Output:     # merged project and employee into final
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny

In [23]:
# merging the final with seniority_level
final = pd.merge(final, seniority_level, on = "ID", how = "left")

In [24]:
# Output:     #final ouput of all the three dataframe files csv merged into one single file ("final")
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3

In [25]:
# save final DataFrame
final.to_csv("final.csv", index = False)

In [26]:
# Output:    final output of saved final.csv file  
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3

In [27]:
# this step not needed if the final csv file output designation level column is created without any x and y designation level while merging
# lets delete one of the column created after merging and rename the column name as per seniority_level dataframe

# final.drop(columns = ["Designation Level_x"], inplace = True)

In [28]:
# Output:    # Final output if we need to drop the column seniority_level_x and seniority_level_y
# final

In [29]:
# rename Designation Level_y to desgination Level

# final.rename(columns = {"Designation Level_y":"Designation Level"}, inplace = True)        -- renaming column

In [30]:
# Output:
# final

In [31]:
# Saving the final Version into Final.csv
final.to_csv("Final.csv", index = False)                # saving the final modified or manipulated version of final DataFrame

## Task 5
Generate a New column called ***Bonus***. and give a ***5%*** bonus to ***finished*** projects. in the ***final*** DataFrame

In [32]:
# Lets Load the data from the final version dataframe final.csv file
final = pd.read_csv("Final.csv")                        # final.csv is loaded as we have created a final version after merging

In [33]:
# Adding a bonus column with a anonymous function for 5% bonus with cost column
final["Bonus"] = final.apply(lambda row: round(row["Cost"] * 0.05, 2) if row["Status"] == "Finished" else 0, axis= 1)

In [34]:
# Save the final DataFrame into Final.csv
final.to_csv("Final.csv", index = False)

In [35]:
# Output:     for Task no 5
final.head(14)

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2,0.0
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,2,0.0
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,3,0.0
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter,2,0.0
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,2,0.0
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,10000.0

## Task 6
***Demote Designation Level by 1*** Where ***final["Status"] == "Fail"*** and Remove Records Who's ***designation Level > 4***

In [36]:
# First load the final dataframe final.csv file
# final= pd.read_csv("Final.csv")       # not needed to load if working with a pipeline as task 5 to 8 or 9 is releated to final dataframe csv file

In [37]:
# Demote designation level by 1 Where final["Status"] == "Failed"
final.loc[final["Status"] == "Failed", "Designation Level"] = final.loc[final["Status"] == "Failed", "Designation Level"] + 1

In [38]:
# Output:      Task no 6
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2,0.0
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,3,0.0
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,4,0.0
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter,2,0.0
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,3,0.0
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,10000.0

In [39]:
# Remove Designation Level > 4
final = final[final["Designation Level"] <= 4]

In [40]:
# save the final DataFrame final.csv file
final.to_csv("Final.csv", index = False)

In [41]:
# Output:     (final dataframe after saving) Task no 6
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2,0.0
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sabestine,3,225000.0
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,3,0.0
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,4,0.0
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter,2,0.0
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3,15000.0
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,3,0.0
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,10000.0

## Task 7
Add ***"Mr." and "Mrs."*** to *First Name* Column and **Drop** ***Gender*** Column

In [42]:
# Load the final dataframe frist                   # not required if not working with indiviual task
# final = pd.read_csv("Final.csv")

In [43]:
# Add Mr. and Mrs. using anonymous function to First Name column series
final["First Name"] = final.apply(lambda row: "Mr. " + row["First Name"] if row["Gender"] == "M" else "Mrs. " + row["First Name"], axis = 1)

In [44]:
# Output:
final                            # added Mr. and Mrs. before first name

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Mrs. Alice,Luxumberg,2,0.0
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Mr. Tom,Sabestine,3,225000.0
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Mrs. Nina,Adgra,2,0.0
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Mrs. Amy,Johny,3,162525.0
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Mrs. Alice,Luxumberg,3,0.0
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Mrs. Amy,Johny,3,20000.0
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Mr. Tom,Sabestine,4,0.0
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,Mr. John,Alter,2,0.0
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Mr. Tom,Sabestine,3,15000.0
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,Mr. John,Alter,3,0.0
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Mrs. Nina,Adgra,2,0.0
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Mrs. Nina,Adgra,2,150000.0
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Mrs. Amy,Johny,3,10000.0

In [45]:
# Remove Gender column
final.drop(columns = ["Gender"], inplace = True)

In [46]:
# save the final Dataframe .csv file 
final.to_csv("Final.csv", index = False)

In [47]:
# Output
final                  # removed Gender column and saved the dataframe

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2.000000e+06,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
2,A003,Project 3,4.500000e+06,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000.0
3,A004,Project 4,5.500000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
4,A005,Project 5,3.250500e+06,Finished,Madrid,30,Mrs. Amy,Johny,3,162525.0
5,A002,Project 6,6.800000e+05,Failed,London,27,Mrs. Alice,Luxumberg,3,0.0
6,A005,Project 7,4.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,3,20000.0
7,A003,Project 8,3.500000e+05,Failed,Berlin,29,Mr. Tom,Sabestine,4,0.0
8,A001,Project 9,2.061714e+06,Ongoing,Paris,25,Mr. John,Alter,2,0.0
9,A003,Project 10,3.000000e+05,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0
10,A001,Project 11,2.000000e+06,Failed,Paris,25,Mr. John,Alter,3,0.0
11,A004,Project 12,1.000000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
12,A004,Project 13,3.000000e+06,Finished,Newyork,31,Mrs. Nina,Adgra,2,150000.0
13,A005,Project 14,2.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,3,10000.0

## Task 8
Promote ***Designation Level by 1*** whoes ***age > 29 years*** using ***(IF condition)***

In [48]:
# Load the dataframe final
# final = pd.read_csv("Final.csv")

In [49]:
# Promote final["Desgnation Level"] - 1 whose age > 29 using IF condition 
final["Designation Level"] = final.apply(lambda row: row["Designation Level"] - 1 if row["Age"] > 29 else row["Designation Level"], axis = 1)

In [50]:
# save the dataframe for Task 8
final.to_csv("Final.csv", index = False)

In [51]:
# Output
final.head(14)        # first 14 rows

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1.002000e+06,Finished,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2.000000e+06,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
2,A003,Project 3,4.500000e+06,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000.0
3,A004,Project 4,5.500000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0.0
4,A005,Project 5,3.250500e+06,Finished,Madrid,30,Mrs. Amy,Johny,2,162525.0
5,A002,Project 6,6.800000e+05,Failed,London,27,Mrs. Alice,Luxumberg,3,0.0
6,A005,Project 7,4.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,2,20000.0
7,A003,Project 8,3.500000e+05,Failed,Berlin,29,Mr. Tom,Sabestine,4,0.0
8,A001,Project 9,2.061714e+06,Ongoing,Paris,25,Mr. John,Alter,2,0.0
9,A003,Project 10,3.000000e+05,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000.0
10,A001,Project 11,2.000000e+06,Failed,Paris,25,Mr. John,Alter,3,0.0
11,A004,Project 12,1.000000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0.0
12,A004,Project 13,3.000000e+06,Finished,Newyork,31,Mrs. Nina,Adgra,1,150000.0
13,A005,Project 14,2.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,2,10000.0

## Task 9
Add the ***Cost of all project*** for ***each employee*** and ***save*** it in
- new DataFrame ***"TotalProjCost"***\
  *with three columns*
1. ID,
2. First Name,
3. Total Cost

In [52]:
# Lets First Load the dataframe file for this task no 9
# final = pd.read_csv("Final.csv")

In [53]:
# using groupby() for ID, First_Name, Total Cost
TotalProjCost = final.groupby(["ID","First Name"])["Cost"].sum().reset_index()

In [54]:
# Before Output with ID, First Name and Cost
TotalProjCost

     ID  First Name          Cost
0  A001    Mr. John  5.063714e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  3.850500e+06

In [55]:
# Lets Rename Cost with Total Cost
TotalProjCost.rename(columns = {"Cost": "Total Cost"}, inplace = True)

In [56]:
# Output After renaming Cost with Total Cost
TotalProjCost

     ID  First Name    Total Cost
0  A001    Mr. John  5.063714e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  3.850500e+06

In [57]:
# Save the TotalProjCost dataframe 
TotalProjCost.to_csv("TotalProjCost.csv", index = False)

## Task 10
Employee Details who's ***city name*** contains ***"o"***

In [58]:
# Load
final = pd.read_csv("Final.csv")                # for exploratary purpose loading final dataframe csv file

In [59]:
# main task
employee_city_name_with_o = final[final["City"].str.contains("o", case = False, na = False )]

In [60]:
# final Exploration output:
employee_city_name_with_o

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,3,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,1,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,1,150000.0

In [61]:
# end